import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'perekup-test-'));
process.env.DATA_DIR=tmp;
process.env.ALLOW_DEV_AUTH='0';
const core=await import('../server.mjs?test='+Date.now());
const {money,levelFromXp,unlockedTier,valueFor,makeFaults,tierMeta,faultCatalog,SEARCH_COST,OFFER_INSPECTION_COST,ROULETTE_PRICES,roulettePriceForTier}=core;
const serverSrc=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const appSrc=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const cssSrc=fs.readFileSync(new URL('../public/styles.css',import.meta.url),'utf8');
const htmlSrc=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');

test('start economy keeps search affordable',()=>assert.ok(100000/SEARCH_COST>=50));
test('inspection price is positive',()=>assert.ok(OFFER_INSPECTION_COST>0));
test('roulette tier prices are configured',()=>assert.deepEqual(ROULETTE_PRICES,{1:65000,2:150000,3:350000,4:750000,5:1500000}));
test('roulette price clamps tiers',()=>{assert.equal(roulettePriceForTier(0),65000);assert.equal(roulettePriceForTier(99),1500000)});
test('money rounds',()=>assert.equal(money(12.6),13));
test('money never negative',()=>assert.equal(money(-50),0));
test('money tolerates bad input',()=>assert.equal(money('x'),0));
test('level starts at 1',()=>assert.equal(levelFromXp(0),1));
test('level 2 at 250 xp',()=>assert.equal(levelFromXp(250),2));
test('level 3 at 500 xp',()=>assert.equal(levelFromXp(500),3));
test('level is capped at 30',()=>assert.equal(levelFromXp(999999),30));
test('negative xp cannot go below level 1',()=>assert.equal(levelFromXp(-999),1));
test('tier 1 at level 1',()=>assert.equal(unlockedTier(1),1));
test('tier 2 at level 3',()=>assert.equal(unlockedTier(3),2));
test('tier 3 at level 6',()=>assert.equal(unlockedTier(6),3));
test('tier 4 at level 10',()=>assert.equal(unlockedTier(10),4));
test('tier 5 at level 15',()=>assert.equal(unlockedTier(15),5));
test('tier metadata has five classes',()=>assert.equal(Object.keys(tierMeta).length,5));
test('tier unlocks are strictly increasing',()=>assert.deepEqual(Object.values(tierMeta).map(x=>x.unlock),[1,3,6,10,15]));
test('fault catalog has unique keys',()=>assert.equal(new Set(faultCatalog.map(x=>x.key)).size,faultCatalog.length));
test('all repair costs are positive',()=>assert.ok(faultCatalog.every(x=>x.cost>0)));
test('all repair gains are bounded',()=>assert.ok(faultCatalog.every(x=>x.gain>0&&x.gain<=20)));
test('valuation decreases for worse condition',()=>{const c={base_price:500000};assert.ok(valueFor(c,2020,50000,90)>valueFor(c,2020,50000,50))});
test('valuation decreases for more mileage',()=>{const c={base_price:500000};assert.ok(valueFor(c,2020,50000,80)>valueFor(c,2020,300000,80))});
test('valuation decreases for older year',()=>{const c={base_price:500000};assert.ok(valueFor(c,2024,50000,80)>valueFor(c,2010,50000,80))});
test('generated faults never exceed four',()=>assert.ok(makeFaults(5,48).length<=4));
test('generated faults use known keys',()=>assert.ok(makeFaults(3,60).every(x=>faultCatalog.some(f=>f.key===x.key))));
test('production dev auth is explicit opt-in',()=>assert.match(serverSrc,/ALLOW_DEV_AUTH=process\.env\.ALLOW_DEV_AUTH==='1'/));
test('server validates Telegram init data',()=>assert.match(serverSrc,/validateInitData/));
test('server limits request body size',()=>assert.match(serverSrc,/body_too_large/));
test('server has CSP',()=>assert.match(serverSrc,/Content-Security-Policy/));
test('Telegram Web iframe is not blocked by X-Frame-Options',()=>assert.doesNotMatch(serverSrc,/X-Frame-Options/));
test('server exposes health endpoint',()=>assert.ok(serverSrc.includes('/healthz')));
test('repeat service is blocked server-side',()=>assert.match(serverSrc,/service_already_done/));
test('service history table exists',()=>assert.match(serverSrc,/vehicle_service_history/));
test('daily progress table exists',()=>assert.match(serverSrc,/daily_task_progress/));
test('daily tasks read date-scoped progress',()=>assert.match(serverSrc,/dailyValue\(user\.id,'inspect'\)/));
test('client uses Telegram stable viewport',()=>assert.match(appSrc,/viewportStableHeight/));
test('client handles Telegram safe area',()=>assert.match(appSrc,/safeAreaInset/));
test('client has API timeout',()=>assert.match(appSrc,/AbortController/));
test('client car photos use Wikimedia with a local visual fallback',()=>{assert.match(appSrc,/CAR_PHOTOS/);assert.match(appSrc,/images\.pexels\.com/);assert.match(appSrc,/PHOTO_POOL/)});
test('client uses emoji icons instead of missing icon assets',()=>{assert.match(appSrc,/EMOJI_ICON/);assert.doesNotMatch(appSrc,/\/assets\/icons\//)});
test('body has no vertical scrolling',()=>assert.match(cssSrc,/html,body\{[^}]*overflow:hidden/));
test('app uses dynamic Telegram viewport height',()=>assert.match(cssSrc,/--app-h:var\(--tg-viewport-stable-height,100dvh\)/));
test('desktop stays phone width',()=>assert.match(cssSrc,/max-width:460px/));
test('system font stack is used',()=>assert.match(cssSrc,/SF Pro Display/));
test('Google Fonts removed',()=>assert.doesNotMatch(htmlSrc,/fonts\.googleapis\.com/));
test('main screens have paginator support',()=>assert.match(appSrc,/function pager\(/));
test('random car roulette animation exists',()=>assert.match(appSrc,/function rouletteOverlay\(/));
test('bottom navigation uses emoji',()=>assert.match(appSrc,/nav-emoji/));
test('white red PEREKUP.RU theme is present',()=>{assert.match(cssSrc,/--p7-red:#ff2b30/);assert.match(appSrc,/ПЕРЕКУП<span>\.RU<\/span>/)});
test('search success has confetti',()=>assert.match(appSrc,/function confetti\(/));
test('roulette buy API exists',()=>assert.match(serverSrc,/\/api\/game\/roulette/));
test('roulette preview API exists',()=>assert.match(serverSrc,/roulette-preview/));
test('roulette button shows purchase price',()=>assert.match(appSrc,/Купить авто/));
test('roulette purchase is server-randomized',()=>assert.match(serverSrc,/generateOffer\(\{\.\.\.fresh,searches:Math\.max\(1,fresh\.searches\)\},tier\)/));
test('garage detail is viewport compact',()=>assert.match(appSrc,/detail-screen/));
test('service list is paginated inside detail',()=>assert.match(appSrc,/pageChunk\(services,'services',4\)/));
test('catalog migrates additively',()=>assert.match(serverSrc,/INSERT OR IGNORE INTO vehicle_catalog/));
test('catalog has a uniqueness index',()=>assert.match(serverSrc,/idx_catalog_unique/));
test('garage shows one car per viewport page',()=>assert.match(appSrc,/pageChunk\(list,'garage',1\)/));
test('ranking page is paginated top five',()=>assert.match(appSrc,/pageChunk\(state\.ranking,'ranking',5\)/));
test('admin page is paginated',()=>assert.match(appSrc,/pageChunk\(a\.users,'admin',3\)/));

test.after(()=>{try{fs.rmSync(tmp,{recursive:true,force:true})}catch{}});
